version: '2'
services:
    backend-kr:
      image: jekyll/jekyll:3.8      
      command: jekyll serve --watch --force_polling --verbose        
      ports:
        - 4000:4000
      volumes:
        - $PWD:/srv/jekyll

